### ISSUE TITLE
Template Header Font Overlap in Safari

### ISSUE THREAD

**Issue by mzagaja** [griffey/15-Lessons#2]
![screenshot 2015-10-22 21 14 13](https://cloud.githubusercontent.com/assets/565647/10682296/e8d2f10a-7901-11e5-9bb7-d089415cb1b7.png)

Not sure if you've noticed this but if the header font goes onto two lines the font will overlap onto itself. Exhibits in the screenshot above. Probably just needs some CSS work I'm happy to contribute a fix as I have time but figured I'd flag this if someone else felt like tackling it.

**Comment by griffey** [comment]
Yep. Got some CSS cleanup to do, but I was going to wait until at least all the text was in place to tackle it. That way if anything else weird showed up I could do it all at once. Thanks for the issue though!

**Comment by mzagaja** [comment]
Sounds like a good plan to me!

**Comment by griffey** [comment]
Fixed in the CSS.
